### ISSUE TITLE
Prewritten script not working properly

### ISSUE THREAD

**Issue by jee-gamer** [knilios/ku-polls#66]
Here's the log after I follow the prewritten script guide and then how to run section
(This is done in powershell)
If it can't be ran in powershell then you should have specified. Since you ran the installation in powershell.
(or am I stupid and it's common sense?)

Basically since it can't activate virtual env it fails.

Installed 5 object(s) from 1 fixture(s)
Installed 58 object(s) from 1 fixture(s)
Installed 3 object(s) from 1 fixture(s)
Initializing environment
"COMPLETED"
PS C:\Users\Jaykayy\ku-polls> cd venv/Scripts
>> activate
>> cd ../..
activate : The term 'activate' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:2 char:1
+ activate
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Jaykayy\ku-polls> python manage.py runserver
Traceback (most recent call last):
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 74, in execute
    super().execute(*args, **options)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 81, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 102, in __getattr__
    self._setup(name)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Jaykayy\ku-polls\mysite\settings.py", line 13, in <module>
    from decouple import config, Csv
ModuleNotFoundError: No module named 'decouple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jaykayy\ku-polls\manage.py", line 22, in <module>
    main()
  File "C:\Users\Jaykayy\ku-polls\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 425, in run_from_argv
    connections.close_all()
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\connection.py", line 84, in close_all
    for conn in self.all(initialized_only=True):
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\connection.py", line 76, in all
    return [
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\connection.py", line 73, in __iter__
    return iter(self.settings)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 102, in __getattr__
    self._setup(name)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\Jaykayy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Jaykayy\ku-polls\mysite\settings.py", line 13, in <module>
    from decouple import config, Csv
ModuleNotFoundError: No module named 'decouple'
PS C:\Users\Jaykayy\ku-polls>

**Comment by knilios** [comment]
It's probably an issue on my end. You were correct for using Powershell.

**Comment by knilios** [comment]
I cannot reproduce the error. Therefore, I have changed the instruction to recommend the user to use Command Prompt instead.
